### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by ogreyesp** [mmalekzadeh/motion-sense#3]
Do data in folder Accelerometer_data comprise user acceleration + gravity combined in single values? i.e. these acceleration values are different to the ones encountered in A_DeviceMotion_data folder, isn't it?

Also I have noted that the length of Accelerometer_data files could be different to the ones in Gyroscope_data folder, Why? If the examples were sampled at the same frequency, the files would have the same size, isn't it?

**Comment by mmalekzadeh** [comment]
1) `Accelerometer` data is equal to `user_acceleration+gravity` in DeviceMotion data. They just come from different APIs in iOS.
2) What you are seeing is normal. Setting a sample rate in iOS (and Android) is just a suggestion to the operating system (i.e. iOS here). Since it is not a real-time system, the actual sampling rate for `Accelerometer` and `Gyroscope` can be a bit different, however very close to what we set that is 50Hz.

**Comment by ogreyesp** [comment]
Thank you so much for your quickly response.
