### ISSUE TITLE
Question on Filtering

### ISSUE THREAD

**Issue by VivekSM1992** [mmalekzadeh/motion-sense#7]
Hello mmalekzadeh,

Do you recommand filtering the sensor data? I know that sensor data comes with has lot of noise in it and it is better to remove noise and feed the data to ML/DL model.  I am no good in signal processing, I did design a low pass filter but output seems worse than original signal. I don't know  to specify the filter specifications(pass band ripple,stop band attenuation, pass band frequency and stop band frequency ).  I just took FFT and felt like frequency of interest is 0 to 15 Hz. Is thee good way to design filter any reference?

**Comment by mmalekzadeh** [comment]
Hey @VivekSM1992 , sorry for the late response. 
I am not an expert in signal processing, but I think it depends on what machine learning algorithm you want to use.
For classical ML algorithms, it might be useful to pre-process signals and perform denoising or extract features.
But if you aim to use neural nets, we usually do not do any pre-processing as a neural net sometimes can generalize better if you feed noisy data into it. Basically, neural nets are feature extractors by design.
